uefivars: add a note that python3-pyuefivars from Noble (1.0.0-0ubuntu2) is broken
When using upstream sources, version 1.0.0 worked but the Ubuntu package one does not:

```
==> Set a valid variable data
+ lxc config uefi set v1 testvar-8be4df61-93ca-11d2-aa0d-00e098032b8c=48656c6c6f2066726f6d204c5844
Error: Failed to run: uefivars.py -i json -o edk2: exit status 1 (Reading uefivars from stdin
Read 41 variables
Traceback (most recent call last):
  File "/snap/lxd/x2/bin/uefivars.py", line 33, in <module>
    sys.exit(load_entry_point('pyuefivars==0.1', 'console_scripts', 'uefivars.py')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/lxd/current/lib/python3/dist-packages/pyuefivars/__init__.py", line 156, in main
    outfile.write(bytes(varstore))
                  ^^^^^^^^^^^^^^^
  File "/snap/lxd/current/lib/python3/dist-packages/pyuefivars/edk2.py", line 295, in __bytes__
    self.blockmap = [(self.length // OVMF_BLOCK_SIZE, OVMF_BLOCK_SIZE)]
                                     ^^^^^^^^^^^^^^^
NameError: name 'OVMF_BLOCK_SIZE' is not defined. Did you mean: 'self.OVMF_BLOCK_SIZE'?)
```

This is due to a regression introduced by an Ubuntu patch:
https://git.launchpad.net/ubuntu/+source/python-uefivars/tree/debian/patches/edk2.py-Improve-firmware-volume-de-serialization.patch?h=ubuntu/noble#n112

This patch was dropped in versions after Noble so we should try to use the
future package that comes with `core26`.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>